validation-rules:
  distance:
    maxKm: 12000
    paxThreshold: 250
    limitedByPaxKm: 8000
  take-off:
    noTakeOffHour: 20
    limitedDistanceTakeOffHour: 14
    limitedKm: 9000
  west-destination:
    noTakeOffHour: 15
    limitedKm: 3000
